# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180810_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(1, 'common'), (2, 'VIP'), (3, 'SVIP')], default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name_plural': '课时'},
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
